"""add empleadas and relacion orden-empleada

Revision ID: c3b49952cc22
Revises: 12f4b8fd1e6d
Create Date: 2025-11-15 20:05:40.615857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b49952cc22'
down_revision = '12f4b8fd1e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empleada_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'empleadas', ['empleada_id'], ['id'])
        batch_op.drop_column('empleada')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empleada', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empleada_id')

    op.drop_table('empleadas')
    # ### end Alembic commands ###
